fonts-linuxlibertine		install
speech-dispatcher-espeak-ng		install
libpackage-stash-perl		install
ca-certificates-java		install
speech-dispatcher-audio-plugins		install
libpam0g		install
ubuntu-settings		install
libmpc3		install
debconf		install
liblog-log4perl-perl		install
libgssapi3-heimdal		install
gkbd-capplet		install
fdisk		install
alsa-topology-conf		install
r-cran-dbitest		install
libgoa-backend-1.0-1		install
texlive-plain-generic		install
r-cran-selectr		install
libchamplain-gtk-0.12-0		install
xserver-xorg-input-all		install
python3-pexpect		install
libjson-glib-1.0-0		install
latex-cjk-japanese		install
evince		install
libxdmcp6		install
r-cran-foreign		install
hunspell-en-us		install
dmz-cursor-theme		install
info		install
libpcre16-3		install
manpages		install
perl-base		install
r-cran-hms		install
libx265-179		install
init		install
r-cran-xml2		install
libc-ares2		install
libqmi-proxy		install
libpolkit-gobject-1-0		install
alsa-base		install
gnome-color-manager		install
fonts-tlwg-laksaman		install
network-manager-pptp		install
libsoup-gnome2.4-1		install
libdjvulibre-text		install
bluez		install
libhttp-daemon-perl		install
init-system-helpers		install
python3-defer		install
latex-cjk-chinese		install
libdevmapper1.02.1		install
gnome-control-center-data		install
fonts-lao		install
libnet-libidn-perl		install
python3-distro-info		install
evolution-data-server-common		install
iso-codes		install
ttf-bitstream-vera		install
libssh2-1		install
default-jre-headless		install
gnome-power-manager		install
r-cran-pkgconfig		install
node-html5shiv		install
fonts-tlwg-purisa-otf		install
libgdata-common		install
libcroco3		install
acpid		install
r-cran-utf8		install
tex-common		install
libwebp6		install
libusb-1.0-0		install
hplip-data		install
gnome-keyring		install
fonts-tlwg-purisa		install
libknopflerfish-osgi-framework-java		install
libqpdf26		install
libldb2		install
libefivar1		install
r-cran-whisker		install
gnome-settings-daemon-common		install
xserver-xorg		install
libhttp-message-perl		install
gnome-shell-extension-prefs		install
dmsetup		install
libpath-tiny-perl		install
libxstream-java		install
r-cran-ini		install
libmoox-aliases-perl		install
libnl-route-3-200		install
fuse		install
r-cran-httpuv		install
libteamdctl0		install
fonts-junicode		install
libkrb5-3		install
dosfstools		install
default-jre		install
libavformat58		install
linux-headers-generic-hwe-20.04		install
r-cran-colorspace		install
libcogl20		install
latexdiff		install
libhawtjni-runtime-java		install
libgssapi-krb5-2		install
xserver-xorg-video-qxl		install
python3-cupshelpers		install
liblouisutdml-data		install
r-cran-tikzdevice		install
libsnappy1v5		install
python3-ibus-1.0		install
xserver-xorg-video-vesa		install
texmaker		install
libperl4-corelibs-perl		install
libservlet3.1-java		install
tracker-extract		install
fonts-lobstertwo		install
libopenjp2-7		install
netplan.io		install
texlive-metapost-doc		install
libmoo-perl		install
node-normalize.css		install
libpangoft2-1.0-0		install
texlive-font-utils		install
texlive-lang-spanish		install
libjpeg-turbo8-dev		install
bind9-dnsutils		install
poppler-utils		install
dbus-x11		install
r-cran-mgcv		install
gnome-shell-extension-desktop-icons		install
libgusb2		install
libb-hooks-op-check-perl		install
libmagick++-6.q16-8		install
bolt		install
libencode-hanextra-perl		install
libavfilter7		install
ubuntu-keyring		install
libwww-robotrules-perl		install
libaa1		install
libnghttp2-14		install
liblapack3		install
gstreamer1.0-alsa		install
libcpanel-json-xs-perl		install
ubuntu-desktop-minimal		install
libgphoto2-port12		install
libseccomp2		install
libpackagekit-glib2-18		install
libcrack2		install
libdata-compare-perl		install
glib-networking-services		install
gnome-accessibility-themes		install
fonts-tlwg-typewriter-otf		install
libraw1394-11		install
libencode-locale-perl		install
texlive-publishers-doc		install
fonts-thai-tlwg		install
libao4		install
diffutils		install
libqt5svg5		install
libieee1284-3		install
linux-headers-5.4.0-26-generic		install
libfontenc1		install
fonts-gubbi		install
libclutter-1.0-0		install
fonts-font-awesome		install
mtr-tiny		install
libxcb-icccm4		install
gir1.2-nm-1.0		install
gir1.2-gtksource-4		install
libaudit-common		install
libclang1-10		install
libplist3		install
sound-theme-freedesktop		install
libcom-err2		install
language-pack-gnome-en		install
libpopt0		install
libvte-2.91-0		install
libedataserverui-1.2-2		install
libcups2		install
fonts-ebgaramond-extra		install
libvulkan1		install
libwayland-egl1		install
libjs-es5-shim		install
gnome-colors-common		install
intel-microcode		install
libmail-sendmail-perl		install
libdbus-1-3		install
irqbalance		install
texlive-latex-base		install
libwind0-heimdal		install
update-manager-core		install
networkd-dispatcher		install
libsemanage1		install
uuid-runtime		install
libmodule-runtime-perl		install
libgtop2-common		install
vprerex		install
xserver-xorg-video-nouveau		install
libchromaprint1		install
fonts-gfs-porson		install
sysvinit-utils		install
fonts-sil-gentiumplus		install
libclutter-gst-3.0-0		install
gedit		install
gnome-human-icon-theme		install
printer-driver-splix		install
libpkcs11-helper1		install
libfdisk1		install
mobile-broadband-provider-info		install
publicsuffix		install
javascript-common		install
libparse-recdescent-perl		install
r-cran-mockery		install
iptables		install
libauthen-sasl-perl		install
netpbm		install
libdrm-nouveau2		install
xserver-xorg-video-amdgpu		install
gnome-session-common		install
gir1.2-gtk-3.0		install
system-config-printer		install
fonts-arphic-gkai00mp		install
gir1.2-mutter-6		install
gnupg-utils		install
gvfs-backends		install
fonts-tlwg-norasi-otf		install
gir1.2-gmenu-3.0		install
libparams-validate-perl		install
libgtksourceview-4-common		install
python3-dateutil		install
libtext-bibtex-perl		install
bc		install
libmtp9		install
os-prober		install
libpcsclite1		install
dc		install
purifyeps		install
ed		install
gnome-logs		install
fonts-indic		install
libxklavier16		install
libpcre3-dev		install
whoopsie		install
latex-cjk-chinese-arphic-gkai00mp		install
libfile-basedir-perl		install
gnome-control-center		install
friendly-recovery		install
iw		install
r-cran-mime		install
session-migration		install
python3-olefile		install
libsasl2-modules-db		install
libnet-ssleay-perl		install
libgcr-base-3-1		install
gir1.2-notify-0.7		install
xserver-common		install
liblist-moreutils-perl		install
printer-driver-c2esp		install
libevdocument3-4		install
libxml-sax-base-perl		install
tk		install
gir1.2-secret-1		install
libxcb-xfixes0		install
vim-common		install
libwacom-common		install
mscompress		install
libzip5		install
libcurl4		install
libbsf-java		install
freeplane		install
libhtml-form-perl		install
fonts-hosny-amiri		install
gir1.2-soup-2.4		install
gnome-chess		install
r-cran-bit64		install
printer-driver-m2300w		install
libtype-tiny-perl		install
libgtk2.0-bin		install
r-cran-labeling		install
gpg-wks-client		install
fonts-beng-extra		install
alsa-ucm-conf		install
feynmf		install
gstreamer1.0-plugins-base-apps		install
libasm-java		install
fragmaster		install
libspeechd2		install
libldap-2.4-2		install
libmpfr6		install
speech-dispatcher		install
libbusiness-isbn-data-perl		install
libegl1		install
r-cran-covr		install
libxapian30		install
app-install-data-partner		install
libdata-dump-perl		install
libmime-charset-perl		install
gcc-9-base		install
python3-software-properties		install
gnome-dust-icon-theme		install
sgml-base		install
libpam-modules		install
gvfs-bin		install
openssl		install
libblockdev-swap2		install
ruby2.7		install
qt5-gtk-platformtheme		install
libnotify-bin		install
bluez-cups		install
xserver-xorg-core		install
libllvm9		install
fonts-tlwg-purisa-ttf		install
printer-driver-hpcups		install
libmagickcore-6.q16-6-extra		install
gnome-system-monitor		install
fonts-stix		install
gir1.2-clutter-1.0		install
strace		install
libgxps2		install
libdv4		install
libdw1		install
libgirepository-1.0-1		install
t1utils		install
libgphoto2-6		install
gir1.2-gdkpixbuf-2.0		install
rake		install
python3-wadllib		install
fonts-tlwg-norasi		install
libopencore-amrnb0		install
fonts-gfs-didot-classic		install
gnupg-l10n		install
libcogl-path20		install
ubuntu-restricted-addons		install
libgdk-pixbuf2.0-0		install
libc6-dbg		install
libfakeroot		install
appstream		install
linux-modules-extra-5.4.0-26-generic		install
fonts-deva		install
libproxy1v5		install
sane-utils		install
libssh-4		install
gnome-user-docs		install
libnorm1		install
intltool-debian		install
libc6-dev		install
dvipng		install
libargon2-1		install
liblcms2-2		install
libgoa-1.0-0b		install
cracklib-runtime		install
libjsp-api-java		install
libegl-mesa0		install
fonts-smc-gayathri		install
foomatic-db-compressed-ppds		install
dconf-service		install
texlive-lang-european		install
python3-xkit		install
libsereal-encoder-perl		install
imagemagick		install
libcairo-gobject2		install
libm17n-0		install
libjpeg-dev		install
update-notifier-common		install
gnome-wise-icon-theme		install
chrome-gnome-shell		install
libdatetime-perl		install
libatk-wrapper-java		install
python3-macaroonbakery		install
va-driver-all		install
libjaxp1.3-java		install
libgoa-1.0-common		install
lib32stdc++6		install
libpython3.8-minimal		install
libhamcrest-java		install
libgamemode0		install
libswresample3		install
libgnome-autoar-gtk-0-0		install
texlive-publishers		install
libcdparanoia0		install
libfprint-2-2		install
python3-distro		install
ntfs-3g		install
libnl-genl-3-200		install
libctf-nobfd0		install
libdata-optlist-perl		install
libwbclient0		install
fonts-guru-extra		install
libtry-tiny-perl		install
apturl-common		install
git-man		install
python3-jwt		install
gnome-sudoku		install
yaru-theme-icon		install
r-cran-promises		install
r-cran-testthat		install
fonts-tlwg-typewriter-ttf		install
libnumber-compare-perl		install
libfile-desktopentry-perl		install
fonts-samyak-deva		install
libbrotli1		install
libsystemd0		install
libxml-sax-perl		install
libgweather-3-16		install
libio-async-perl		install
libpulsedsp		install
ruby-net-telnet		install
glib-networking		install
fonts-telu-extra		install
libgtk-3-common		install
acl		install
libarchive-zip-perl		install
base-passwd		install
gstreamer1.0-tools		install
fonts-smc		install
r-cran-crayon		install
laptop-detect		install
dash		install
gcc-10-base		install
xdg-user-dirs		install
libhttp-negotiate-perl		install
grub-common		install
libpciaccess0		install
fonts-tlwg-typist		install
libpam-fprintd		install
libjs-twitter-bootstrap-datepicker		install
fonts-gargi		install
libpgm-5.2-0		install
ant		install
r-cran-png		install
r-cran-diffobj		install
fonts-deva-extra		install
libgslcblas0		install
apg		install
apt		install
r-cran-rcolorbrewer		install
libxcb-present0		install
libgtk-3-0		install
libgd3		install
libacl1		install
libvariable-magic-perl		install
gnome-brave-icon-theme		install
libheimntlm0-heimdal		install
libshout3		install
openvpn		install
libparted2		install
iucode-tool		install
cups-pk-helper		install
libksba8		install
libavahi-glib1		install
libgl1		install
r-cran-rsqlite		install
wireless-tools		install
libgjs0g		install
texlive-luatex		install
darcula		install
libtcl8.6		install
gnome-wine-icon-theme		install
libzmq5		install
pulseaudio		install
fonts-smc-karumbi		install
gstreamer1.0-plugins-good		install
libjcommander-java		install
libobjc4		install
libgs9		install
python3-systemd		install
libipc-system-simple-perl		install
seahorse		install
latex-cjk-chinese-arphic-bkai00mp		install
fonts-adf-gillius		install
cpp-9		install
fonts-tlwg-norasi-ttf		install
gsettings-ubuntu-schemas		install
libcogl-common		install
efibootmgr		install
libedata-cal-2.0-1		install
dbus		install
xul-ext-ubufox		install
libtext-csv-xs-perl		install
libsratom-0-0		install
libpng-dev		install
libkmod2		install
freeglut3		install
libglapi-mesa		install
gnome-desktop3-data		install
policykit-desktop-privileges		install
yelp		install
libyelp0		install
r-cran-data.table		install
libjs-jquery-selectize.js		install
libpsl5		install
debconf-i18n		install
libpixman-1-0		install
fonts-kalapi		install
libasound2-data		install
texlive-science-doc		install
texlive-lang-greek		install
libxkbfile1		install
libdbusmenu-glib4		install
openjade		install
libalgorithm-diff-perl		install
libmount1		install
fprintd		install
libdevel-callchecker-perl		install
fonts-ebgaramond		install
tcpdump		install
rtkit		install
libpst4		install
libproxy1-plugin-gsettings		install
snapd		install
libipc-shareable-perl		install
libperlio-utf8-strict-perl		install
libpam-cap		install
libatkmm-1.6-1v5		install
bogofilter-bdb		install
libsigc++-2.0-0v5		install
lib32gcc-s1		install
latex-cjk-all		install
libcommons-logging-java		install
printer-driver-foo2zjs		install
libsecret-1-0		install
libsqlite3-0		install
fonts-urw-base35		install
update-manager		install
liborc-0.4-0		install
librsvg2-common		install
libalgorithm-merge-perl		install
libxrender1		install
printer-driver-postscript-hp		install
libemail-valid-perl		install
libwoff1		install
ubuntu-advantage-tools		install
r-cran-rex		install
gnome-games		install
libbz2-1.0		install
libcdio18		install
libicu66		install
libelf1		install
python3-protobuf		install
gamemode		install
python3-urllib3		install
simplyhtml		install
binutils		install
gir1.2-atk-1.0		install
fonts-cantarell		install
libcommons-cli-java		install
libencode-perl		install
r-cran-generics		install
gnome-klotski		install
cpp		install
libmagickwand-6.q16-6		install
fonts-noto-cjk		install
squashfs-tools		install
libgpgme11		install
fonts-navilu		install
texlive-games		install
r-cran-askpass		install
bsdmainutils		install
r-cran-bh		install
r-cran-bitops		install
r-cran-vdiffr		install
libwhoopsie0		install
libogg0		install
libigdgmm11		install
r-cran-dt		install
libxcb-render-util0		install
libstruct-dumb-perl		install
libb-hooks-endofscope-perl		install
libgpg-error0		install
libopenmpt0		install
r-cran-fs		install
r-cran-gh		install
humanity-icon-theme		install
r-cran-pillar		install
libsnmp-base		install
libjs-mathjax		install
python3-aptdaemon.gtk3widgets		install
gnome-icon-theme		install
libbsd0		install
bind9-host		install
language-selector-common		install
liblouis20		install
libpstoedit0c2a		install
libtracker-sparql-2.0-0		install
r-cran-ps		install
r-cran-r6		install
texlive-fonts-recommended-doc		install
r-cran-sp		install
libsort-key-perl		install
libarchive13		install
e2fsprogs		install
python3-reportlab-accel		install
libamtk-5-common		install
libemf1		install
libpoppler-qt5-1		install
zlib1g		install
r-cran-curl		install
libitm1		install
docbook-xml		install
r-cran-littler		install
libalgorithm-c3-perl		install
fonts-smc-chilanka		install
liblilv-0-0		install
libdvdread7		install
fonts-orya		install
lshw		install
libwrap0		install
libpcre2-32-0		install
p11-kit		install
rstudio		install
r-cran-sys		install
libexception-class-perl		install
libavahi-common-data		install
lsof		install
xserver-xorg-video-fbdev		install
libqmi-glib5		install
python3-gi-cairo		install
r-cran-fansi		install
powermgmt-base		install
pptp-linux		install
libgspell-1-common		install
at-spi2-core		install
libgmp10		install
r-cran-multicore		install
fonts-gfs-complutum		install
linux-sound-base		install
libgfortran-9-dev		install
texlive-lang-english		install
fonts-unfonts-extra		install
texlive-lang-german		install
bogofilter-common		install
xdg-dbus-proxy		install
libexporter-tiny-perl		install
g++		install
iagno		install
fonts-go		install
r-cran-lubridate		install
libefiboot1		install
libhttp-date-perl		install
dconf-gsettings-backend		install
libgail-common		install
liblist-allutils-perl		install
gdebi-core		install
eog		install
gfortran		install
r-cran-runit		install
perl-modules-5.30		install
libavahi-common3		install
r-cran-withr		install
libxcb-util1		install
liblwp-mediatypes-perl		install
libspecio-perl		install
r-cran-later		install
libiw30		install
libunity-protocol-private0		install
sudo		install
gir1.2-geoclue-2.0		install
r-cran-reshape2		install
libqt5dbus5		install
ubuntu-wallpapers-focal		install
patchutils		install
libvdpau1		install
google-chrome-stable		install
libncurses6		install
libclass-singleton-perl		install
libxml-commons-external-java		install
r-cran-clisymbols		install
dnsmasq-base		install
ubuntu-standard		install
python3-brlapi		install
libcdio-cdda2		install
libmp3lame0		install
python3-pil		install
libbabeltrace1		install
libgtk2.0-0		install
libgdata22		install
liba52-0.7.4		install
anacron		install
lmodern		install
fonts-mathjax		install
python3-keyring		install
libheimbase1-heimdal		install
xfonts-utils		install
gir1.2-accountsservice-1.0		install
nodejs		install
fonts-gfs-artemisia		install
libc6		install
ubuntu-session		install
r-cran-gdtools		install
libasync-mergepoint-perl		install
console-setup-linux		install
nano		install
gnome-noble-icon-theme		install
linux-base		install
r-cran-gtable		install
gpg-wks-server		install
libpeas-1.0-0		install
netbase		install
fonts-tlwg-kinnari		install
fonts-pagul		install
libxcursor1		install
fonts-tlwg-mono		install
texinfo		install
ftp		install
libjs-sifter.js		install
texlive-base		install
libjansi-java		install
util-linux		install
gir1.2-unity-5.0		install
libnuma1		install
python3-entrypoints		install
libnet-dns-perl		install
libjs-jquery-datatables-extensions		install
libclass-c3-xs-perl		install
python3-netifaces		install
libpython3.8		install
libptexenc1		install
libimagequant0		install
ubuntu-desktop		install
libclang-10-dev		install
python3.8		install
xserver-xorg-input-libinput		install
libjs-jquery		install
libextutils-pkgconfig-perl		install
fonts-kacst-one		install
fonts-gfs-theokritos		install
python-apt-common		install
gcc		install
gcr		install
gdb		install
libgnome-bluetooth13		install
fonts-knda		install
xserver-xorg-legacy		install
r-cran-plyr		install
coreutils		install
libfile-slurper-perl		install
liblist-utilsby-perl		install
libmodule-implementation-perl		install
r-cran-testit		install
liblocale-gettext-perl		install
git		install
libgphoto2-l10n		install
r-cran-tinytex		install
gjs		install
gnome-session-canberra		install
r-cran-webutils		install
libxatracker2		install
lcdf-typetools		install
gnome-settings-daemon		install
plymouth-label		install
libpackage-stash-xs-perl		install
libgupnp-1.2-0		install
texlive-fonts-extra		install
libthai-data		install
libqt5widgets5		install
gpg		install
fonts-gfs-didot		install
python3		install
libiconloader-java		install
python3-pyatspi		install
r-cran-sodium		install
libblockdev-crypto2		install
libtext-levenshtein-perl		install
libbrlapi0.7		install
libperlio-gzip-perl		install
libdevel-lexalias-perl		install
python3-louis		install
fonts-smc-meera		install
printer-driver-min12xxw		install
libcogl-pango20		install
libsepol1		install
libstrictures-perl		install
fonts-lobster		install
libpolkit-agent-1-0		install
libk5crypto3		install
texlive-humanities-doc		install
gir1.2-pango-1.0		install
grub2-common		install
liblapack-dev		install
iputils-tracepath		install
mousetweaks		install
libharfbuzz-icu0		install
fonts-unfonts-core		install
libsub-quote-perl		install
python3-idna		install
libvorbisfile3		install
node-highlight.js		install
printer-driver-pxljr		install
x11-apps		install
gnome-mahjongg		install
libdaemon0		install
evolution-common		install
libmtdev1		install
xbrlapi		install
libip6tc2		install
fonts-droid-fallback		install
udev		install
fonts-tlwg-kinnari-otf		install
libopencore-amrwb0		install
locales		install
libwacom-bin		install
console-setup		install
mime-support		install
fonts-smc-raghumalayalamsans		install
r-cran-hexbin		install
r-cran-blob		install
gstreamer1.0-plugins-base		install
fonts-gfs-baskerville		install
cups-server-common		install
xinit		install
libxcb-shm0		install
texlive-metapost		install
r-cran-rprojroot		install
python3-lazr.restfulclient		install
libepoxy0		install
libfastjson4		install
libnm0		install
libsub-identify-perl		install
popularity-contest		install
libpwquality-common		install
evolution-data-server		install
plymouth-theme-ubuntu-text		install
libpcre32-3		install
passwd		install
r-cran-htmlwidgets		install
texlive-latex-extra-doc		install
libappindicator3-1		install
procps		install
libsecret-common		install
python3-six		install
libwhoopsie-preferences0		install
inputattach		install
gsettings-desktop-schemas		install
libsasl2-2		install
libsub-exporter-perl		install
libtype-tiny-xs-perl		install
libipc-run3-perl		install
r-cran-htmltools		install
whoopsie-preferences		install
alsa-utils		install
libgraphene-1.0-0		install
insync		install
zlib1g-dev		install
r-cran-mockr		install
r-cran-filehash		install
r-cran-xml		install
libnftnl11		install
x11-xkb-utils		install
libasan5		install
gnome-screenshot		install
network-manager-gnome		install
r-cran-systemfonts		install
libgles2		install
teckit		install
libdatetime-format-builder-perl		install
libbz2-dev		install
libxcb-randr0		install
readline-common		install
fonts-tibetan-machine		install
texlive-pictures		install
libgail18		install
r-cran-class		install
libxcb-render0		install
language-pack-en		install
libu2f-udev		install
ivy		install
libfont-ttf-perl		install
libblockdev-loop2		install
libquadmath0		install
libklibc		install
libpam-runtime		install
orca		install
libregexp-common-perl		install
libclass-xsaccessor-perl		install
libdatetime-calendar-julian-perl		install
lightsoff		install
libxalan2-java		install
libhyphen0		install
libwww-perl		install
ttf-mscorefonts-installer		install
libxstring-perl		install
libpipeline1		install
upower		install
xdg-utils		install
libx11-protocol-perl		install
r-cran-r.methodss3		install
isc-dhcp-common		install
libcommons-io-java		install
libblockdev-fs2		install
gnome-colors		install
gir1.2-freedesktop		install
amd64-microcode		install
gdm3		install
libtotem-plparser-common		install
yaru-theme-gtk		install
libgsf-1-114		install
libhandy-0.0-0		install
libparams-util-perl		install
libwmf0.2-7		install
iio-sensor-proxy		install
cups-common		install
fonts-ipaexfont-gothic		install
libmagic1		install
libbusiness-ismn-perl		install
nautilus-extension-gnome-terminal		install
sound-icons		install
libio-html-perl		install
python3-lazr.uri		install
xkb-data		install
fonts-arphic-bkai00mp		install
bubblewrap		install
libytnef0		install
fonts-sahadeva		install
libisc-export1105		install
libencode-eucjpms-perl		install
libxmlgraphics-commons-java		install
texmaker-data		install
r-cran-progress		install
libassuan0		install
network-manager		install
libdevel-caller-perl		install
r-cran-r.oo		install
gdebi		install
packagekit-tools		install
libntfs-3g883		install
libwavpack1		install
gnome-bluetooth		install
libbdplus0		install
libmutter-6-0		install
libmpdec2		install
software-properties-gtk		install
lacheck		install
kbd		install
dkms		install
initramfs-tools-bin		install
libbusiness-issn-perl		install
libqqwing2v5		install
librygel-server-2.6-2		install
libyaml-tiny-perl		install
r-cran-freetypeharfbuzz		install
liblist-someutils-perl		install
texlive-lang-french		install
linux-image-generic-hwe-20.04		install
ssl-cert		install
xserver-xorg-input-wacom		install
grub-pc		install
colord-data		install
libblockdev-part2		install
libncursesw6		install
libapache-pom-java		install
libgudev-1.0-0		install
r-cran-shiny		install
texlive-fonts-recommended		install
r-cran-purrr		install
fontconfig-config		install
libnet-http-perl		install
libtepl-4-0		install
libatk-adaptor		install
groovy		install
libgamemodeauto0		install
vdpau-driver-all		install
libprocps8		install
libcanberra-gtk3-module		install
libparted-fs-resize0		install
p11-kit-modules		install
r-cran-boot		install
emacs-bin-common		install
openjdk-11-jre-headless		install
fonts-tlwg-typewriter		install
libx11-6		install
linux-modules-5.4.0-26-generic		install
libxmlb1		install
pfb2t1c2pfb		install
libopus0		install
libapt-pkg6.0		install
librubberband2		install
libgexiv2-2		install
fonts-smc-keraleeyam		install
libsub-install-perl		install
latex-cjk-chinese-arphic-gbsn00lp		install
python3-requests		install
r-cran-cluster		install
libgpars-groovy-java		install
five-or-more		install
libisl22		install
fonts-lohit-deva		install
debianutils		install
gir1.2-gdm-1.0		install
fonts-oflb-asana-math		install
libexpat1		install
memtest86+		install
libpostproc55		install
glib-networking-common		install
fonts-smc-suruma		install
texlive-lang-cyrillic		install
dvisvgm		install
python3-httplib2		install
libgstreamer-plugins-good1.0-0		install
kmod		install
gnome-shell-extension-draw-on-your-screen		install
r-cran-mapproj		install
libudev1		install
libvpx6		install
libunicode-utf8-perl		install
rsyslog		install
libfido2-1		install
libdvdnav4		install
libpango-perl		install
libgcr-ui-3-1		install
fonts-tlwg-garuda		install
libapparmor1		install
libcrypt1		install
libnet-smtp-ssl-perl		install
libsoup2.4-1		install
r-cran-markdown		install
texlive-xetex		install
python3-cups		install
lz4		install
emacs-el		install
fonts-sil-abyssinica		install
libjgoodies-common-java		install
tracker-miner-fs		install
r-cran-magrittr		install
ruby-minitest		install
libtalloc2		install
libio-socket-ssl-perl		install
libdata-uniqid-perl		install
libqt5xml5		install
libdynaloader-functions-perl		install
gtk2-engines-murrine		install
libwebpdemux2		install
xcursor-themes		install
ibus-gtk		install
libtracker-miner-2.0-0		install
libdigest-bubblebabble-perl		install
libpam-gnome-keyring		install
libexempi8		install
adduser		install
libltdl7		install
gnome-disk-utility		install
gstreamer1.0-pulseaudio		install
libgbm1		install
libfprint-2-tod1		install
libstdc++-9-dev		install
fonts-taml		install
build-essential		install
ibus-gtk3		install
x11-session-utils		install
r-cran-rpart		install
evolution-rss		install
libxshmfence1		install
libfile-fcntllock-perl		install
mutter-common		install
fonts-tlwg-kinnari-ttf		install
texlive-latex-extra		install
libpaper1		install
geoclue-2.0		install
libclang-dev		install
libapt-pkg-perl		install
libplymouth5		install
preview-latex-style		install
libatk-wrapper-java-jni		install
libaom0		install
krb5-locales		install
libgsl23		install
libxkbcommon-x11-0		install
libqt5printsupport5		install
liblmdb0		install
libclass-inspector-perl		install
r-cran-abind		install
r-cran-scales		install
systemd-timesyncd		install
libfuture-perl		install
texlive-lang-portuguese		install
libgcc1		install
gnome-tweaks		install
python3-renderpm		install
libsm6		install
apturl		install
gir1.2-gnomedesktop-3.0		install
libgeocode-glib0		install
python3-xdg		install
python3-pymacaroons		install
libgeoclue-2-0		install
dirmngr		install
libss2		install
librygel-db-2.6-2		install
linux-image-5.4.0-37-generic		install
r-cran-kernsmooth		install
r-cran-cliapp		install
mount		install
pandoc		install
fonts-adf-universalis		install
libndp0		install
r-cran-brew		install
python3-simplejson		install
libusbmuxd6		install
hoichess		install
linux-generic-hwe-20.04		install
libwayland-client0		install
fonts-samyak-taml		install
libspectre1		install
libcairo-perl		install
aisleriot		install
libdatetime-format-strptime-perl		install
libperl5.30		install
r-cran-yaml		install
libespeak-ng1		install
ps2eps		install
libaspell15		install
libsemanage-common		install
r-cran-matrix		install
libsombok3		install
libxml-commons-resolver1.1-java		install
libref-util-perl		install
samba-libs		install
libgnome-todo		install
binutils-x86-64-linux-gnu		install
libstartup-notification0		install
biber		install
grub-pc-bin		install
xserver-xephyr		install
fonts-gfs-solomos		install
sbsigntool		install
libcdio-paranoia2		install
xorg-docs-core		install
libext2fs2		install
fonts-tlwg-waree		install
r-cran-fastmap		install
libfile-sharedir-perl		install
libpangoxft-1.0-0		install
ubuntu-minimal		install
apport		install
libbtparse2		install
gnome-extra-icons		install
libgdm1		install
libmanette-0.2-0		install
gnome-font-viewer		install
evolution-plugin-bogofilter		install
libattr1		install
texlive-fonts-extra-doc		install
lib32gcc1		install
gnome-paint		install
libcrypt-dev		install
nautilus-share		install
gir1.2-gck-1		install
gdisk		install
libdrm-amdgpu1		install
r-cran-ellipsis		install
fonts-crosextra-carlito		install
libinput-bin		install
texlive-music		install
r-cran-fontliberation		install
gnome-calculator		install
libnfnetlink0		install
fonts-tlwg-typo		install
libmtp-runtime		install
libblkid1		install
fonts-gfs-bodoni-classic		install
libwmf0.2-7-gtk		install
liblqr-1-0		install
libboost-dev		install
libexif12		install
xml-core		install
libosp5		install
libllvm10		install
libhtml-tagset-perl		install
libebackend-1.2-10		install
dpkg		install
context		install
cups-filters		install
fonts-ubuntu		install
libuv1		install
fontconfig		install
libmediaart-2.0-0		install
fonts-noto-color-emoji		install
libdist-checkconflicts-perl		install
fonts-lklug-sinhala		install
libparams-classify-perl		install
imagemagick-6.q16		install
gir1.2-cogl-1.0		install
libtiff5		install
libqt5gui5		install
evince-common		install
groff-base		install
udisks2		install
ruby-xmlrpc		install
r-cran-processx		install
ppp		install
libva2		install
xdg-desktop-portal-gtk		install
libsnmp35		install
libjansi-native-java		install
libfile-mimeinfo-perl		install
libclass-method-modifiers-perl		install
libmnemonicsetter-java		install
libgnome-autoar-0-0		install
libotf0		install
libboost1.71-dev		install
libao-common		install
python3-minimal		install
ubuntu-drivers-common		install
gvfs-libs		install
gvfs-fuse		install
nautilus		install
libxau6		install
python3-speechd		install
libpeas-common		install
libnautilus-extension1a		install
ubuntu-docs		install
libxaw7		install
libtsan0		install
libfile-listing-perl		install
libtext-csv-perl		install
libgnome-desktop-3-19		install
libclone-perl		install
jmapviewer		install
r-cran-git2r		install
fonts-telu		install
fonts-lohit-orya		install
libgee-0.8-2		install
gir1.2-wnck-3.0		install
libatk1.0-0		install
libsub-name-perl		install
r-cran-spatial		install
librtmp1		install
libxcomposite1		install
grub-efi-amd64-bin		install
gir1.2-peas-1.0		install
gnome-sound-recorder		install
r-cran-vctrs		install
adwaita-icon-theme		install
libx264-155		install
python3-cryptography		install
busybox-static		install
libgtk-3-bin		install
libnss-mdns		install
python3-distupgrade		install
r-base-core		install
hitori		install
libc-bin		install
libcommons-parent-java		install
libsmbios-c2		install
r-cran-rcpp		install
r-cran-clipr		install
man-db		install
libmagic-mgc		install
libsasl2-modules		install
texlive-bibtex-extra		install
libubsan1		install
libpangocairo-1.0-0		install
libboost-thread1.71.0		install
libebook-1.2-20		install
libmime-lite-perl		install
libdatetime-timezone-perl		install
libpulse0		install
unrar		install
libzzip-0-13		install
pci.ids		install
r-cran-assertthat		install
python3-debconf		install
libunicode-linebreak-perl		install
yelp-xsl		install
libdevel-size-perl		install
libass9		install
cups-ppdc		install
fonts-gfs-gazis		install
python3-commandnotfound		install
fonts-baekmuk		install
gir1.2-graphene-1.0		install
psmisc		install
libtotem-plparser18		install
libmpg123-0		install
gir1.2-glib-2.0		install
g++-9		install
libsysmetrics1		install
libxvidcore4		install
fonts-sil-gentium-basic		install
gir1.2-vte-2.91		install
fonts-comfortaa		install
fonts-tlwg-waree-otf		install
python3-update-manager		install
libtinfo6		install
libruby2.7		install
libcaca0		install
libxcb-image0		install
libxcb1		install
sgml-data		install
grub-gfxpayload-lists		install
libevview3-3		install
libchamplain-0.12-0		install
libimobiledevice6		install
gir1.2-gweather-3.0		install
kerneloops		install
prerex		install
liblwp-protocol-https-perl		install
libxtst6		install
r-cran-munsell		install
fonts-arphic-bsmi00lp		install
libatspi2.0-0		install
gir1.2-snapd-1		install
libjs-highlight.js		install
printer-driver-sag-gdi		install
libsvgsalamander-java		install
r-cran-fontbitstreamvera		install
ubuntu-release-upgrader-core		install
fonts-glyphicons-halflings		install
m17n-db		install
texlive-lang-other		install
libatm1		install
r-cran-sourcetools		install
librsvg2-2		install
r-cran-sessioninfo		install
python3-apport		install
im-config		install
libxi6		install
pkg-config		install
libkrb5support0		install
librole-tiny-perl		install
fonts-tlwg-sawasdee		install
gtk2-engines-pixbuf		install
tali		install
network-manager-openvpn		install
libjbig2dec0		install
libavcodec-extra		install
libjcsp-java		install
latex-cjk-chinese-arphic-bsmi00lp		install
libiec61883-0		install
ruby		install
r-cran-codetools		install
libilmbase24		install
libzvbi0		install
texlive-lang-korean		install
libxt6		install
hplip		install
libpcre3		install
liblouisutdml9		install
libxv1		install
sed		install
whiptail		install
avahi-daemon		install
wbritish		install
emacs-gtk		install
gir1.2-gnomebluetooth-1.0		install
fonts-tlwg-umpush		install
libvorbisenc2		install
libjs-d3		install
libfwupdplugin1		install
libnewt0.52		install
libnet-dbus-perl		install
texlive-full		install
libtag1v5		install
libcap2		install
libxcb-res0		install
libdee-1.0-4		install
libpython3-stdlib		install
python3-cffi-backend		install
fonts-tlwg-garuda-otf		install
libfuse2		install
libgfortran5		install
fonts-lohit-knda		install
libcupsfilters1		install
r-cran-usethis		install
littler		install
make		install
libhpmud0		install
python3.8-minimal		install
fonts-smc-rachana		install
dmidecode		install
fonts-tlwg-sawasdee-otf		install
libgstreamer-gl1.0-0		install
fonts-ipaexfont-mincho		install
libmspack0		install
libpulse-mainloop-glib0		install
libemail-date-format-perl		install
evolution-plugin-pstimport		install
libjlatexmath-java		install
libgif7		install
fonts-tlwg-loma		install
language-pack-gnome-en-base		install
libxinerama1		install
libsonic0		install
tar		install
systemd-sysv		install
fakeroot		install
tcl		install
firefox-locale-en		install
mawk		install
xserver-xorg-video-intel		install
libgsf-1-common		install
libcap2-bin		install
libblockdev2		install
libspeex1		install
libuuid1		install
r-cran-rlang		install
chromium-codecs-ffmpeg-extra		install
libantlr-java		install
openjdk-11-jre		install
libhtml-tree-perl		install
guile-2.2-libs		install
libnl-3-200		install
texlive-pstricks-doc		install
libldap-common		install
r-cran-digest		install
libavalon-framework-java		install
fonts-arphic-gbsn00lp		install
libxml-libxslt-perl		install
libavahi-core7		install
libaacs0		install
fonts-smc-manjari		install
r-cran-jsonlite		install
libgdbm6		install
texlive-humanities		install
gcc-9		install
libio-stringy-perl		install
libobjc-9-dev		install
libgcrypt20		install
libimport-into-perl		install
fonts-tlwg-typo-otf		install
fonts-dejavu-core		install
libjack-jackd2-0		install
libbatik-java		install
acpi-support		install
libxcb-xinerama0		install
r-cran-fontquiver		install
libhcrypto4-heimdal		install
libxml-twig-perl		install
libtexluajit2		install
ucf		install
libxcb-keysyms1		install
r-doc-html		install
libglib2.0-bin		install
ufw		install
libpdfbox-java		install
libnamespace-clean-perl		install
libkeyutils1		install
espeak-ng-data		install
libxmuu1		install
libqt5script5		install
r-cran-desc		install
gnome-tetravex		install
fonts-gujr		install
libxcb-xv0		install
libpcre2-dev		install
lintian		install
libmailtools-perl		install
brltty		install
r-cran-devtools		install
libunity9		install
fonts-guru		install
linux-modules-extra-5.4.0-37-generic		install
fonts-sil-gentiumplus-compact		install
gnome-shell-common		install
libdevel-globaldestruction-perl		install
libxft2		install
r-cran-listenv		install
libjs-jquery-datatables		install
zenity		install
perl-openssl-defaults		install
ibus-table		install
r-cran-globals		install
libnetfilter-conntrack3		install
liblist-someutils-xs-perl		install
libc6-i386		install
fonts-dejavu-extra		install
libpaper-utils		install
libselinux1		install
libvo-amrwbenc0		install
liblz4-1		install
libgtksourceview-4-0		install
libpcre2-8-0		install
python3-blinker		install
context-modules		install
gpgv		install
libglew2.1		install
tk8.6		install
libncurses5-dev		install
libnet-dns-sec-perl		install
libmm-glib0		install
libjson-glib-1.0-common		install
gfortran-9		install
gir1.2-gcr-3		install
libgck-1-0		install
libjs-jquery-ui		install
libpam-systemd		install
libxfont2		install
xserver-xorg-video-vmware		install
libxrandr2		install
libgstreamer-plugins-base1.0-0		install
libgail-3-0		install
system-config-printer-udev		install
libreadonly-perl		install
libavutil56		install
xwayland		install
libtie-ixhash-perl		install
distro-info-data		install
libtheora0		install
texlive-lang-italian		install
libsndfile1		install
fonts-smc-uroob		install
libdatetime-locale-perl		install
fonts-tlwg-loma-otf		install
libjpeg8		install
xz-utils		install
fonts-samyak-gujr		install
parted		install
libdrm2		install
libnma0		install
gedit-common		install
libtext-wrapi18n-perl		install
python3-yaml		install
gnome-startup-applications		install
libxcb-shape0		install
fonts-crosextra-caladea		install
r-cran-rstudioapi		install
gstreamer1.0-x		install
python3-pkg-resources		install
libbusiness-isbn-perl		install
fonts-tlwg-waree-ttf		install
libpcaudio0		install
libyaml-libyaml-perl		install
libautovivification-perl		install
libio-async-loop-epoll-perl		install
libcommons-codec-java		install
r-cran-stringi		install
r-cran-stringr		install
libcanberra-pulse		install
ghostscript		install
libglx0		install
tcl8.6		install
packagekit		install
libcolord2		install
liblsan0		install
fonts-nakula		install
gir1.2-goa-1.0		install
shared-mime-info		install
fonts-gfs-olga		install
plymouth-theme-spinner		install
systemd		install
libgomp1		install
libmozjs-68-0		install
libvolume-key1		install
fonts-lohit-beng-bengali		install
libproxy1-plugin-networkmanager		install
usb.ids		install
libwebkit2gtk-4.0-37		install
libdbus-glib-1-2		install
gnome-online-accounts		install
libsmartcols1		install
gir1.2-upowerglib-1.0		install
libqt5core5a		install
libgme0		install
rfkill		install
libmbim-proxy		install
libcanberra-gtk3-0		install
latex-cjk-korean		install
wpasupplicant		install
libtest-refcount-perl		install
libxerces2-java		install
texlive-pstricks		install
libgdk-pixbuf2.0-bin		install
asymptote-doc		install
grep		install
openprinting-ppds		install
libutempter0		install
login		install
libfontembed1		install
libssh-gcrypt-4		install
libgspell-1-2		install
gir1.2-atspi-2.0		install
linux-headers-5.4.0-26		install
libglu1-mesa		install
linux-headers-5.4.0-37		install
python3-rfc3339		install
hicolor-icon-theme		install
usb-modeswitch-data		install
libglib-perl		install
gir1.2-gst-plugins-base-1.0		install
ruby-power-assert		install
libplot2c2		install
rygel		install
fonts-tlwg-garuda-ttf		install
libfont-afm-perl		install
liblog-dispatch-perl		install
fonts-orya-extra		install
libhttp-cookies-perl		install
libenchant-2-2		install
fonts-ipafont-gothic		install
libxfixes3		install
fonts-tlwg-mono-otf		install
xxd		install
xserver-xorg-video-all		install
libthai0		install
libsoxr0		install
fonts-tlwg-sawasdee-ttf		install
libwebpmux3		install
gnome-todo-common		install
gnome-shell-extension-appindicator		install
libxml-namespacesupport-perl		install
libxml-libxml-simple-perl		install
xserver-xorg-video-ati		install
libijs-0.35		install
eject		install
libio-string-perl		install
libhogweed5		install
r-cran-praise		install
nautilus-sendto		install
mysql-common		install
libxxf86dga1		install
emacsen-common		install
libio-pty-perl		install
ncurses-bin		install
r-cran-roxygen2		install
libdevel-stacktrace-perl		install
libwebsocket-api-java		install
libestr0		install
libfontconfig1		install
libwnck-3-0		install
libpam-modules-bin		install
libjs-bootstrap		install
r-cran-evaluate		install
libasyncns0		install
fonts-glewlwyd		install
fonts-mlym		install
apt-utils		install
libx11-data		install
libblockdev-utils2		install
mokutil		install
iproute2		install
libfile-homedir-perl		install
ghostscript-x		install
libgnome-games-support-common		install
libgl1-mesa-dri		install
libswscale5		install
aspell		install
libgnome-games-support-1-3		install
fonts-lohit-taml		install
libtext-glob-perl		install
libxml-libxml-perl		install
fonts-tlwg-typo-ttf		install
libreadline8		install
liblingua-translit-perl		install
libcairomm-1.0-1v5		install
libjs-prettify		install
libupower-glib3		install
libostyle1c2		install
libgdk-pixbuf2.0-common		install
libsmbclient		install
libopenexr24		install
libpadwalker-perl		install
unzip		install
yaru-theme-gnome-shell		install
xorg		install
libspeexdsp1		install
libmpeg2-4		install
texlive-fonts-extra-links		install
openssh-client		install
libfwupd2		install
fonts-beng		install
libdb5.3		install
libjs-json		install
libmysofa1		install
r-cran-memoise		install
enchant-2		install
libsodium23		install
libgnome-menu-3-0		install
aptdaemon-data		install
zip		install
libmagickcore-6.q16-6		install
libdns-export1109		install
libsord-0-0		install
iputils-ping		install
libgtk2.0-common		install
liblouisutdml-bin		install
libservlet-api-java		install
r-cran-rmarkdown		install
libtdb1		install
r-recommended		install
libnfs13		install
shim-signed		install
texlive-lang-czechslovak		install
libvidstab1.1		install
manpages-dev		install
libmysqlclient21		install
r-cran-base64enc		install
libnss-systemd		install
libgs9-common		install
bzip2		install
gnome-initial-setup		install
fwupd-signed		install
avahi-autoipd		install
keyboard-configuration		install
bsdutils		install
fonts-samyak-mlym		install
libxpp3-java		install
tracker		install
gnome-shell-extensions		install
gsfonts		install
gir1.2-dbusmenu-glib-0.4		install
binutils-common		install
apt-config-icons-hidpi		install
python3-dbus		install
libasound2		install
libgssdp-1.2-0		install
texlive-lang-arabic		install
libsane-hpaio		install
network-manager-config-connectivity-ubuntu		install
fonts-tlwg-typist-otf		install
psutils		install
libsynctex2		install
fonts-yrsa-rasa		install
time		install
icc-profiles-free		install
usbutils		install
libblockdev-part-err2		install
libnetplan0		install
gnome-session-bin		install
tipa		install
libasound2-plugins		install
x11-xserver-utils		install
rubygems-integration		install
libunwind8		install
genisoimage		install
libgraphite2-3		install
libgpm2		install
libxxf86vm1		install
libtss2-esys0		install
libgcc-s1		install
linux-headers-5.4.0-37-generic		install
libfftw3-double3		install
libcheese-gtk25		install
plymouth		install
libjpeg-turbo8		install
junit4		install
emacs		install
libuchardet0		install
r-cran-lifecycle		install
libsaxon-java		install
python3-talloc		install
r-cran-farver		install
libidw-java		install
libvisual-0.4-0		install
r-cran-commonmark		install
libgsound0		install
libgcab-1.0-0		install
gnome-characters		install
libglib2.0-data		install
ltrace		install
libnettle7		install
cheese-common		install
bluez-obexd		install
libfontbox-java		install
language-pack-en-base		install
fonts-lato		install
libncurses-dev		install
switcheroo-control		install
libdbusmenu-gtk3-4		install
javahelp2		install
fonts-tlwg-loma-ttf		install
liblist-compare-perl		install
libcolord-gtk1		install
printer-driver-pnm2ppa		install
ncurses-base		install
libxtables12		install
nodejs-doc		install
libxdamage1		install
gir1.2-gdesktopenums-3.0		install
fonts-khmeros-core		install
r-cran-tibble		install
cups-filters-core-drivers		install
libjgoodies-forms-java		install
bash		install
librest-0.7-0		install
gir1.2-coglpango-1.0		install
dictionaries-common		install
policykit-1		install
bogofilter		install
r-cran-highr		install
gvfs		install
file-roller		install
libshine3		install
gnome-control-center-faces		install
code		install
r-cran-tidyselect		install
ibus		install
libdjvulibre21		install
libatk-bridge2.0-0		install
thermald		install
libpwquality1		install
python3-cairo		install
gstreamer1.0-libav		install
tex-gyre		install
cabextract		install
python3-aptdaemon		install
lsb-release		install
xserver-xorg-video-radeon		install
apport-gtk		install
r-cran-callr		install
libtimedate-perl		install
usbmuxd		install
gnome-nibbles		install
libphonenumber7		install
ubuntu-release-upgrader-gtk		install
libjbig0		install
findutils		install
libsidplay1v5		install
libc-dev-bin		install
intel-media-va-driver		install
libcap-ng0		install
texlive-formats-extra		install
libxml2		install
grub-efi-amd64-signed		install
fonts-smc-dyuthi		install
file		install
ubuntu-wallpapers		install
libsane-common		install
libmaxminddb0		install
python3-gi		install
pstoedit		install
libept1.6.0		install
libvte-2.91-common		install
libdigest-hmac-perl		install
libcommons-lang-java		install
fonts-opensymbol		install
r-cran-pkgbuild		install
libxmu6		install
logrotate		install
pciutils		install
fonts-lmodern		install
linux-headers-surface		install
texlive-binaries		install
gir1.2-packagekitglib-1.0		install
fonts-roboto-unhinted		install
libflac8		install
libnet-domain-tld-perl		install
fwupd		install
xfonts-base		install
libidn11		install
python3-tz		install
libbinutils		install
aglfn		install
libpcre2-posix2		install
fonts-noto-core		install
libebook-contacts-1.2-3		install
qttranslations5-l10n		install
gir1.2-webkit2-4.0		install
r-cran-httr		install
cpio		install
libpython3.8-stdlib		install
gnome-terminal-data		install
r-cran-prettyunits		install
libgnutls30		install
python3-ptyprocess		install
unattended-upgrades		install
libtracker-control-2.0-0		install
libibus-1.0-5		install
pulseaudio-module-bluetooth		install
r-cran-pkgload		install
libnss3		install
libedit2		install
gnome-todo		install
lm-sensors		install
libdrm-intel1		install
libgupnp-dlna-2.0-3		install
latex-cjk-japanese-wadalab		install
libwacom2		install
libnode64		install
libwnck-3-common		install
libroken18-heimdal		install
libcapture-tiny-perl		install
fonts-lohit-telu		install
libedata-book-1.2-26		install
fonts-tlwg-mono-ttf		install
libpcap0.8		install
libsensors-config		install
r-cran-backports		install
fonts-kacst		install
libtwolame0		install
libclass-data-inheritable-perl		install
r-cran-future		install
libfreetype6		install
libcairo-gobject-perl		install
libudisks2-0		install
libclang-common-10-dev		install
gir1.2-ibus-1.0		install
ca-certificates		install
fonts-texgyre		install
r-cran-openssl		install
libel-api-java		install
liblouis-data		install
python3-oauthlib		install
libicu-dev		install
libgsm1		install
libva-x11-2		install
python3-launchpadlib		install
firefox		install
libva-wayland2		install
libcodec2-0.9		install
perl		install
rsync		install
pandoc-data		install
libcheese8		install
fonts-croscore		install
xauth		install
modemmanager		install
quadrapassel		install
gvfs-common		install
libffi7		install
vim-tiny		install
apparmor		install
libecal-2.0-1		install
fonts-gujr-extra		install
librhino-java		install
libunistring2		install
command-not-found		install
gnome-taquin		install
dns-root-data		install
texlive-lang-japanese		install
python3-nacl		install
gdbserver		install
libp11-kit0		install
libjpeg8-dev		install
libasn1-8-heimdal		install
cm-super		install
libzstd1		install
r-cran-knitr		install
lsb-base		install
network-manager-openvpn-gnome		install
libbs2b0		install
hardinfo		install
gnome-keyring-pkcs11		install
libpng-tools		install
libkrb5-26-heimdal		install
wget		install
spice-vdagent		install
nautilus-data		install
gnome-shell		install
libgc1c2		install
gir1.2-gstreamer-1.0		install
four-in-a-row		install
cups-bsd		install
libcryptsetup12		install
libglibmm-2.4-1v5		install
libxres1		install
crda		install
telnet		install
r-cran-domc		install
avahi-utils		install
libical3		install
python3-requests-unixsocket		install
x11-common		install
libappstream4		install
fonts-freefont-otf		install
gnome-mines		install
gtk-update-icon-cache		install
texlive-lang-cjk		install
fonts-sil-gentium		install
libblas-dev		install
libdrm-radeon1		install
cron		install
libxml-parser-perl		install
libxvmc1		install
mtools		install
libsnapd-glib1		install
r-cran-foreach		install
libva-drm2		install
libpangomm-1.4-1v5		install
libxpm4		install
fonts-tlwg-umpush-otf		install
libhunspell-1.7-0		install
librygel-core-2.6-2		install
dbus-user-session		install
libnetpbm10		install
usb-modeswitch		install
x11-utils		install
mesa-vdpau-drivers		install
aptdaemon		install
cups-core-drivers		install
fonts-tlwg-typist-ttf		install
linux-firmware		install
libunity-scopes-json-def-desktop		install
libjline2-java		install
ocl-icd-libopencl1		install
mesa-vulkan-drivers		install
libatomic1		install
gir1.2-json-1.0		install
libxml-sax-expat-perl		install
libvorbis0a		install
libpoppler-cpp0v5		install
logsave		install
librygel-renderer-2.6-2		install
cups-daemon		install
libencode-jis2k-perl		install
fonts-tlwg-laksaman-otf		install
libssl1.1		install
gzip		install
fonts-sil-padauk		install
libv4l-0		install
fonts-adf-berenis		install
fonts-smc-anjalioldlipi		install
libatk1.0-data		install
texlive-science		install
accountsservice		install
libeval-closure-perl		install
libavcodec-extra58		install
libharfbuzz0b		install
libsub-exporter-progressive-perl		install
gnome-themes-extra-data		install
r-cran-remotes		install
language-selector-gnome		install
libgnomekbd8		install
libgtk3-perl		install
libqt5network5		install
gir1.2-polkit-1.0		install
libfile-find-rule-perl		install
libglib-object-introspection-perl		install
libtasn1-6		install
gnupg		install
asymptote		install
libcc1-0		install
libtext-roman-perl		install
libv4lconvert0		install
system-config-printer-common		install
emacs-common		install
ruby-test-unit		install
libpci3		install
libjansson4		install
libextutils-depends-perl		install
libblas3		install
libprotobuf17		install
gstreamer1.0-clutter-3.0		install
icu-devtools		install
libref-util-xs-perl		install
libtag1v5-vanilla		install
libjs-modernizr		install
libreadline-dev		install
libpcrecpp0v5		install
libyaml-0-2		install
libjson-c4		install
libgdbm-compat4		install
r-cran-xfun		install
latexmk		install
libcamel-1.2-62		install
netcat-openbsd		install
texlive-latex-recommended-doc		install
libbluetooth3		install
fonts-lohit-beng-assamese		install
synaptic		install
libice6		install
i965-va-driver		install
libstemmer0d		install
ubuntu-report		install
r-cran-nlme		install
gettext-base		install
ubuntu-restricted-extras		install
apport-symptoms		install
xfonts-encodings		install
r-base-dev		install
libcolorhug2		install
r-cran-bit		install
xinput		install
python3-reportlab		install
libcanberra0		install
linux-image-surface		install
gettext		install
gstreamer1.0-vaapi		install
libcairo2		install
libcupsimage2		install
pinentry-curses		install
libsereal-decoder-perl		install
texlive-lang-chinese		install
fonts-lohit-gujr		install
xbitmaps		install
libexiv2-27		install
linux-modules-5.4.0-37-generic		install
libmultiverse-core-java		install
libtext-iconv-perl		install
r-cran-lattice		install
fonts-ipafont-mincho		install
python3-debian		install
libpoppler-glib8		install
xfonts-scalable		install
printer-driver-ptouch		install
libipc-run-perl		install
fonts-lohit-guru		install
pinentry-gnome3		install
liblzma5		install
dvidvi		install
libavc1394-0		install
libgnomekbd-common		install
libclutter-1.0-common		install
libstdc++6		install
libdotconf0		install
evolution-plugins		install
libnpth0		install
python3-gdbm		install
libpoppler97		install
libavahi-client3		install
fonts-noto-mono		install
libxcb-glx0		install
libzvbi-common		install
gnome-terminal		install
cups		install
pulseaudio-utils		install
libdate-simple-perl		install
curl		install
gstreamer1.0-packagekit		install
libdpkg-perl		install
libtk8.6		install
ibus-data		install
libpango-1.0-0		install
r-cran-glue		install
apt-config-icons		install
libserd-0-0		install
gnome-themes-extra		install
libhx509-5-heimdal		install
r-cran-cli		install
libtest-fatal-perl		install
libxss1		install
libfontbox2-java		install
libjsr166y-java		install
texlive-pictures-doc		install
desktop-file-utils		install
isc-dhcp-client		install
secureboot-db		install
libtexlua53		install
poppler-data		install
libxcb-xinput0		install
fonts-liberation		install
r-cran-prettycode		install
libip4tc2		install
libtevent0		install
libxcb-dri2-0		install
libteckit0		install
libgupnp-av-1.0-2		install
libxkbcommon0		install
fonts-cabin		install
cups-client		install
libjavascriptcoregtk-4.0-18		install
cups-ipp-utils		install
klibc-utils		install
dconf-cli		install
texlive-latex-recommended		install
libmbim-glib4		install
gir1.2-rsvg-2.0		install
python3-certifi		install
liblcms2-utils		install
r-cran-nnet		install
libclass-accessor-perl		install
bzip2-doc		install
libjs-microplugin.js		install
libqdox-java		install
patch		install
libhtml-parser-perl		install
libpcre2-16-0		install
r-cran-dbi		install
libsensors5		install
libgstreamer-plugins-bad1.0-0		install
network-manager-pptp-gnome		install
gpg-agent		install
python3-secretstorage		install
update-notifier		install
xdg-user-dirs-gtk		install
python3-chardet		install
r-cran-plogr		install
libgstreamer1.0-0		install
ant-optional		install
libcbor0.6		install
libalgorithm-diff-xs-perl		install
python3-problem-report		install
libparams-validationcompiler-perl		install
liblinux-epoll-perl		install
xdg-desktop-portal		install
libnotify4		install
liburi-perl		install
libsamplerate0		install
latex-cjk-thai		install
libtext-unidecode-perl		install
ubuntu-mono		install
gvfs-daemons		install
libedataserver-1.2-24		install
r-cran-maps		install
r-cran-dplyr		install
libclass-c3-perl		install
libxcb-dri3-0		install
r-cran-mass		install
libjson-maybexs-perl		install
java-common		install
libglib2.0-0		install
libdconf1		install
wireless-regdb		install
r-cran-xopen		install
libidn2-0		install
install-info		install
r-cran-rcmdcheck		install
fonts-freefont-ttf		install
libmtp-common		install
libsys-hostname-long-perl		install
liblzma-dev		install
antlr		install
fonts-liberation2		install
libbluray2		install
r-cran-lazyeval		install
gnome-robots		install
libgtk2-perl		install
pcmciautils		install
fonts-tlwg-umpush-ttf		install
bind9-libs		install
gir1.2-handy-0.0		install
libgweather-common		install
libfop-java		install
libatasmart4		install
libnet-ip-perl		install
texlive-extra-utils		install
fonts-open-sans		install
libnspr4		install
fonts-gfs-neohellenic		install
zenity-common		install
libaudit1		install
r-cran-survival		install
libsereal-perl		install
libcurl3-gnutls		install
initramfs-tools-core		install
sensible-utils		install
gnome-getting-started-docs		install
gpgconf		install
texlive-lang-polish		install
java-wrappers		install
gir1.2-nma-1.0		install
fonts-tlwg-laksaman-ttf		install
libsane		install
fonts-adf-accanthis		install
libdata-url-java		install
gnome-backgrounds		install
libtie-cycle-perl		install
libevolution		install
initramfs-tools		install
libwayland-server0		install
libxcb-xkb1		install
printer-driver-foo2zjs-common		install
libflite1		install
tpm-udev		install
less		install
gstreamer1.0-gl		install
evolution		install
libatopology2		install
gir1.2-dee-1.0		install
wamerican		install
r-cran-iterators		install
hostname		install
libjsyntaxpane-java		install
libaribb24-0		install
libx11-xcb1		install
libmnl0		install
libdebconfclient0		install
update-inetd		install
texlive-latex-base-doc		install
fonts-sarai		install
python3-apt		install
libmro-compat-perl		install
libfribidi0		install
libxcb-sync1		install
libgtop-2.0-11		install
libaccountsservice0		install
r-cran-rversions		install
libsbc1		install
r-cran-ggplot2		install
gir1.2-javascriptcoregtk-4.0		install
libinput10		install
fonts-lohit-mlym		install
hdparm		install
fonts-lohit-taml-classical		install
linux-libc-dev-surface		install
swell-foop		install
ippusbxd		install
libctf0		install
diffstat		install
cups-browsed		install
colord		install
gnome-illustrious-icon-theme		install
libgcc-9-dev		install
libmime-types-perl		install
libnamespace-autoclean-perl		install
libfile-which-perl		install
r-cran-crosstalk		install
mutter		install
mesa-va-drivers		install
libclutter-gtk-1.0-0		install
libxslt1.1		install
libamtk-5-0		install
base-files		install
xterm		install
linux-image-5.4.0-26-generic		install
gpgsm		install
dpkg-dev		install
libtext-charwidth-perl		install
bash-completion		install
libfftw3-single3		install
gnome-shell-extension-ubuntu-dock		install
libxext6		install
imagemagick-6-common		install
gstreamer1.0-plugins-ugly		install
libdouble-conversion3		install
aspell-en		install
libdatrie1		install
chktex		install
libsigsegv2		install
tzdata		install
libxml-xpathengine-perl		install
libglx-mesa0		install
yaru-theme-sound		install
printer-driver-brlaser		install
libglvnd0		install
libwebrtc-audio-processing1		install
libdrm-common		install
libgtkmm-3.0-1v5		install
liblzo2-2		install
busybox-initramfs		install
libkpathsea6		install
libxml-writer-perl		install
gnome-menus		install
libcue2		install
r-cran-viridislite		install
latex-cjk-common		install
cm-super-minimal		install
libwayland-cursor0		install
r-cran-xtable		install
libslang2		install
r-cran-pkgkitten		install
libhtml-format-perl		install
software-properties-common		install
liberror-perl		install
libpng16-16		install
shim		install
libevdev2		install
